"""empty message

Revision ID: ae907ca549a9
Revises: 84b04e28a2d5
Create Date: 2023-09-20 15:01:46.777070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae907ca549a9'
down_revision = '84b04e28a2d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_product', schema=None) as batch_op:
        batch_op.drop_column('its_promo')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('its_promo', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('its_promo')

    with op.batch_alter_table('order_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('its_promo', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
